##### introduction to pandas

pandas is a python package providing fast, flexble, and expressive data structures designed to make working with "relational" or "labeled" data both easy and intutive

Here are just a few of the things that pandas does well: it has functions for analyzing, cleaning, exploring, and manipulating data.

The name "pandas" has a refernce to both "panel data", and "python data analysis" and was created by Wes McKinney in 2008


##### pandas applications

easy handling of missing data.

size mutability: columns can be inserted and deleted from DataFrame and higher dimensional objects.

automatic and explicit data alignment: objects can be explicitly aligned to a set of labels, or the user can simply ignore the labels and let series, DataFrame etc.

Automatically align the data for you in computations

Powerful, flexible group by functionality.

Intelligent label-based sliciing. fancy indexing, and subsetting of large data sets.

Intutive merging and joining data sets.

Flexible reshaping and pivoting of data sets.

##### Data Structures in

The best way to think about the pandas data structures is as flexble containers for lower dimensional data. For example, DataFrame is a container for SEries, and Series is a container for scalars. We would like to be able to insert and remove objects form these containers in a dictionary-like fahion.


##### Series in pandas:

Pandas series is a one-dimensional labeled array capable of holding data of any type (integer, string float, python objects, etc) The axis labels are collectively called indes. Pandas series is nothing but a column in an excel sheet.

The object supports both integer and label-based indexing and provides a host of methods for performing operations involving the index.


##### DataFrames:

Pandas DataFrame is two-dimensional size-mutable, potentially heterogeneous tabular data structure with labeled axes (rows and columns). A Data frame is two-dimensional data structure. i.3., data is aligned in a tabular fashion in rows and columns. Pandas DataFrame consists of three principal components, the data, rows, and columns.

##### Creation of dataframes in pandas

In [138]:
import pandas as pd 

data = {"Name": ["John", "Peter", "Lisa"],
        "Age": [25, 28, 31],
        "Salary" : [300000, 45000, 25000]}

df = pd.DataFrame(data)
print (df)

    Name  Age  Salary
0   John   25  300000
1  Peter   28   45000
2   Lisa   31   25000

In [139]:
data = pd.read_csv("company.csv")
print (data)

   Unnamed: 0      Name gender  salary
0           0    ayushi      F   20000
1           1     rohit      M   25000
2           2  pranjali      F   27000

In [140]:
data2 = pd.read_excel("expense3.xlsx")
print(data2)

         Date    Category       Sub-Category   Amount Payment Mode
0  2023-01-01     Grocery             Grocery      30         Cash
1  2023-01-02        Food          Restaurant     890          UPI
2  2023-01-04         123              Zomato     257          NaN
3  2023-01-06  Essentials               Diary     120          UPI
4  2023-01-06  Essentials             Perfume    1500         Cash
5  2023-01-09     Grocery  Fruits and Veggies     456         Cash
6  2023-01-10       Bills          House Rent   16000          UPI
7  2023-01-10     Grocery      Tomato KetchUp      70          UPI
8  2023-01-12        Food                Chai      15          UPI
9  2023-01-15  Essentials      Salt and Sugar      50          NaN
10 2023-01-17     Grocery           Chocolate     100          UPI
11 2023-01-17        Food          Restaurant     780         Card
12 2023-01-18  Essentials            Food Oil     120          NaN
13 2023-01-18        Food              Zomato     230          UPI
14 2023-01-19     Grocery                Milk      26          UPI
15 2023-01-20  Essentials             Shampoo     780          UPI
16 2023-01-20  Essentials           Lunch Box     890         Cash
17 2023-01-21     Clothes               Dress    1000          NaN
18 2023-01-22     Clothes               Dress    1890          UPI
19 2023-01-23     Grocery      Bread and Milk      56         Cash
20 2023-01-24        Food  Fruits and Veggies     530         Cash
21 2023-01-26        Food                Chai      10          UPI
22 2023-01-26     Grocery               Maggi     140          UPI
23 2023-01-27        Food              Zomato     300          UPI
24 2023-01-27        Food                Chai      10          UPI
25 2023-01-28  Essentials           Bedsheets    1025         Cash
26 2023-01-29       Bills             Mobile     1650          UPI
27 2023-01-29     Grocery                Daal     150         Cash
28 2023-01-30       Bills            Cylinder    1074          UPI

##### Exploring Data in Pandas

In [141]:
data = pd.read_excel("ESD.xlsx")
print(data.head(10))
print(data.tail(10))

     EEID        Full Name                 Job Title  Department  \
0  E02387      Emily Davis                Sr. Manger          IT
1  E04105    Theodore Dinh       Technical Architect          IT
2  E02572     Luna Sanders                  Director     Finance
3  E02832  Penelope Jordan  Computer Systems Manager          IT
4  E01639        Austin Vo               Sr. Analyst     Finance
5  E00644     Joshua Gupta    Account Representative       Sales
6  E01550      Ruby Barnes                   Manager          IT
7  E04332      Luke Martin                   Analyst     Finance
8  E04533    Easton Bailey                   Manager  Accounting
9  E03838  Madeline Walker               Sr. Analyst     Finance

            Business Unit  Gender  Ethnicity  Age  Hire Date  Annual Salary  \
0  Research & Development  Female      Black   55 2016-04-08         141604
1           Manufacturing    Male      Asian   59 1997-11-29          99975
2     Speciality Products  Female  Caucasian   50 2006-10-26         163099
3           Manufacturing  Female  Caucasian   26 2019-09-27          84913
4           Manufacturing    Male      Asian   55 1995-11-20          95409
5               Corporate    Male      Asian   57 2017-01-24          50994
6               Corporate  Female  Caucasian   27 2020-07-01         119746
7           Manufacturing    Male      Black   25 2020-05-16          41336
8           Manufacturing    Male  Caucasian   29 2019-01-25         113527
9     Speciality Products  Female  Caucasian   34 2018-06-13          77203

   Bonus %        Country       City  Exit Date
0     0.15  United States    Seattle 2021-10-16
1     0.00          China  Chongqing        NaT
2     0.20  United States    Chicago        NaT
3     0.07  United States    Chicago        NaT
4     0.00  United States    Phoenix        NaT
5     0.00          China  Chongqing        NaT
6     0.10  United States    Phoenix        NaT
7     0.00  United States      Miami 2021-05-20
8     0.06  United States     Austin        NaT
9     0.00  United States    Chicago        NaT
       EEID          Full Name             Job Title       Department  \
990  E01578       Anthony Hong            Sr. Manger               IT
991  E03430        Leo Herrera  Sr. Business Partner  Human Resources
992  E03058      Robert Wright   Technical Architect               IT
993  E04762  Audrey Richardson              Director               IT
994  E01148     Scarlett Kumar       Systems Analyst               IT
995  E03094       Wesley Young           Sr. Analyst        Marketing
996  E01909       Lillian Khan               Analyst          Finance
997  E04398        Oliver Yang              Director        Marketing
998  E02521        Lily Nguyen           Sr. Analyst          Finance
999  E03545        Sofia Cheng        Vice President       Accounting

              Business Unit  Gender  Ethnicity  Age  Hire Date  Annual Salary  \
990  Research & Development    Male      Asian   37 2010-11-29         146961
991  Research & Development    Male     Latino   48 1998-04-22          85369
992           Manufacturing    Male  Caucasian   30 2015-06-14          67489
993           Manufacturing  Female  Caucasian   46 2018-10-06         166259
994               Corporate  Female      Asian   55 2009-01-07          47032
995     Speciality Products    Male  Caucasian   33 2016-09-18          98427
996     Speciality Products  Female      Asian   44 2010-05-31          47387
997     Speciality Products    Male      Asian   31 2019-06-10         176710
998     Speciality Products  Female      Asian   33 2012-01-28          95960
999               Corporate  Female      Asian   63 2020-07-26         216195

     Bonus %        Country      City  Exit Date
990     0.11  United States  Columbus        NaT
991     0.00         Brazil    Manaus 2004-11-27
992     0.00  United States   Chicago        NaT
993     0.17  United States   Chicago        NaT
994     0.00  United States  Columbus        NaT
995     0.00  United States  Columbus        NaT
996     0.00          China   Chengdu 2018-01-08
997     0.15  United States     Miami        NaT
998     0.00          China   Chengdu        NaT
999     0.31  United States     Miami        NaT

In [142]:
print(data.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 14 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   EEID           1000 non-null   object
 1   Full Name      1000 non-null   object
 2   Job Title      1000 non-null   object
 3   Department     1000 non-null   object
 4   Business Unit  1000 non-null   object
 5   Gender         1000 non-null   object
 6   Ethnicity      1000 non-null   object
 7   Age            1000 non-null   int64
 8   Hire Date      1000 non-null   datetime64[ns]
 9   Annual Salary  1000 non-null   int64
 10  Bonus %        1000 non-null   float64
 11  Country        1000 non-null   object
 12  City           1000 non-null   object
 13  Exit Date      85 non-null     datetime64[ns]
dtypes: datetime64[ns](2), float64(1), int64(2), object(9)
memory usage: 109.5+ KB
None

In [143]:
data.describe()

,Age,Hire Date,Annual Salary,Bonus %,Exit Date
count,1000.000000,1000,1000.000000,1000.000000,85
mean,44.382000,2012-04-07 02:54:14.400000,113217.365000,0.088660,2016-11-02 18:04:14.117647104
min,25.000000,1992-01-09 00:00:00,40063.000000,0.000000,1994-12-18 00:00:00
25%,35.000000,2007-02-14 00:00:00,71430.250000,0.000000,2014-12-25 00:00:00
50%,45.000000,2014-02-15 12:00:00,96557.000000,0.000000,2019-05-23 00:00:00
75%,54.000000,2018-06-22 00:00:00,150782.250000,0.150000,2021-04-09 00:00:00
max,65.000000,2021-12-26 00:00:00,258498.000000,0.400000,2022-08-17 00:00:00
std,11.246981,NaN,53545.985644,0.117856,NaN

In [144]:
print(data.isnull().sum())

EEID               0
Full Name          0
Job Title          0
Department         0
Business Unit      0
Gender             0
Ethnicity          0
Age                0
Hire Date          0
Annual Salary      0
Bonus %            0
Country            0
City               0
Exit Date        915
dtype: int64

##### Handling Duplicate Values in Pandas

In [145]:
data = pd.read_csv("company1.csv")
print(data)

    EEID      Name gender   salary
0  EMP01    ayushi      F      NaN
1  EMP02     rohit      M  25000.0
2  EMP03  pranjali    NaN  27000.0
3  EMP01    ayushi      F  20000.0
4  EMP05       NaN      M  25000.0
5  EMP06     rohit      M      NaN
6  EMP02     rohit      M  25000.0

In [146]:
print(data["EEID"].duplicated().sum())

2

In [147]:
print(data.drop_duplicates("EEID")) # hapus kolom EEID yg ada duplicate nya

    EEID      Name gender   salary
0  EMP01    ayushi      F      NaN
1  EMP02     rohit      M  25000.0
2  EMP03  pranjali    NaN  27000.0
4  EMP05       NaN      M  25000.0
5  EMP06     rohit      M      NaN

In [148]:
print(data.drop_duplicates("Name")) # hapus kolom Name yang ada duplicatenya

    EEID      Name gender   salary
0  EMP01    ayushi      F      NaN
1  EMP02     rohit      M  25000.0
2  EMP03  pranjali    NaN  27000.0
4  EMP05       NaN      M  25000.0

##### Working with missing data in pandas ( missing value )

In [149]:
data = pd.read_csv("company1.csv")
print(data)

    EEID      Name gender   salary
0  EMP01    ayushi      F      NaN
1  EMP02     rohit      M  25000.0
2  EMP03  pranjali    NaN  27000.0
3  EMP01    ayushi      F  20000.0
4  EMP05       NaN      M  25000.0
5  EMP06     rohit      M      NaN
6  EMP02     rohit      M  25000.0

In [150]:
print(data.isnull().sum())

EEID      0
Name      1
gender    1
salary    2
dtype: int64

In [151]:
print(data.dropna())

    EEID    Name gender   salary
1  EMP02   rohit      M  25000.0
3  EMP01  ayushi      F  20000.0
6  EMP02   rohit      M  25000.0

In [152]:
import numpy as np
print(data.replace(np.nan, 30000))

    EEID      Name gender   salary
0  EMP01    ayushi      F  30000.0
1  EMP02     rohit      M  25000.0
2  EMP03  pranjali  30000  27000.0
3  EMP01    ayushi      F  20000.0
4  EMP05     30000      M  25000.0
5  EMP06     rohit      M  30000.0
6  EMP02     rohit      M  25000.0

In [153]:
data["salary"] = data["salary"].replace(np.nan, 24400)
print(data)

print("\n mean value in salary : ", data["salary"].mean())

    EEID      Name gender   salary
0  EMP01    ayushi      F  24400.0
1  EMP02     rohit      M  25000.0
2  EMP03  pranjali    NaN  27000.0
3  EMP01    ayushi      F  20000.0
4  EMP05       NaN      M  25000.0
5  EMP06     rohit      M  24400.0
6  EMP02     rohit      M  25000.0

 mean value in salary :  24400.0

In [154]:
data = pd.read_csv("company1.csv")
print(data.fillna(method = "bfill")) # mengisi nilai NaN dengan nilai setelahnya

    EEID      Name gender   salary
0  EMP01    ayushi      F  25000.0
1  EMP02     rohit      M  25000.0
2  EMP03  pranjali      F  27000.0
3  EMP01    ayushi      F  20000.0
4  EMP05     rohit      M  25000.0
5  EMP06     rohit      M  25000.0
6  EMP02     rohit      M  25000.0

C:\Users\hp\AppData\Local\Temp\ipykernel_10652\3704544162.py:2: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  print(data.fillna(method = "bfill")) # mengisi nilai NaN dengan nilai setelahnya

In [155]:
data = pd.read_csv("company1.csv")
print(data.fillna(method = "ffill")) # mengisi nilai NaN dengan nilai sebelumnya

    EEID      Name gender   salary
0  EMP01    ayushi      F      NaN
1  EMP02     rohit      M  25000.0
2  EMP03  pranjali      M  27000.0
3  EMP01    ayushi      F  20000.0
4  EMP05    ayushi      M  25000.0
5  EMP06     rohit      M  25000.0
6  EMP02     rohit      M  25000.0

C:\Users\hp\AppData\Local\Temp\ipykernel_10652\1477396088.py:2: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  print(data.fillna(method = "ffill")) # mengisi nilai NaN dengan nilai sebelumnya

In [156]:
data = pd.read_csv("company1.csv")
print(data.fillna("hi")) # mengisi nilai NaN dengan nilai tertenu

    EEID      Name gender   salary
0  EMP01    ayushi      F       hi
1  EMP02     rohit      M  25000.0
2  EMP03  pranjali     hi  27000.0
3  EMP01    ayushi      F  20000.0
4  EMP05        hi      M  25000.0
5  EMP06     rohit      M       hi
6  EMP02     rohit      M  25000.0

##### columns tranformation in pandas part-1

In [157]:
df = pd.read_excel("ESD.xlsx")
df.head()

,EEID,Full Name,Job Title,Department,Business Unit,Gender,Ethnicity,Age,Hire Date,Annual Salary,Bonus %,Country,City,Exit Date
0,E02387,Emily Davis,Sr. Manger,IT,Research & Development,Female,Black,55,2016-04-08,141604,0.15,United States,Seattle,2021-10-16
1,E04105,Theodore Dinh,Technical Architect,IT,Manufacturing,Male,Asian,59,1997-11-29,99975,0.00,China,Chongqing,NaT
2,E02572,Luna Sanders,Director,Finance,Speciality Products,Female,Caucasian,50,2006-10-26,163099,0.20,United States,Chicago,NaT
3,E02832,Penelope Jordan,Computer Systems Manager,IT,Manufacturing,Female,Caucasian,26,2019-09-27,84913,0.07,United States,Chicago,NaT
4,E01639,Austin Vo,Sr. Analyst,Finance,Manufacturing,Male,Asian,55,1995-11-20,95409,0.00,United States,Phoenix,NaT

In [158]:
df.loc[(df["Bonus %"] == 0), "GetBonus"] = "no bonus"
df.loc[(df["Bonus %"] > 0, "GetBonus")] = "bonus"
df.head()

,EEID,Full Name,Job Title,Department,Business Unit,Gender,Ethnicity,Age,Hire Date,Annual Salary,Bonus %,Country,City,Exit Date,GetBonus
0,E02387,Emily Davis,Sr. Manger,IT,Research & Development,Female,Black,55,2016-04-08,141604,0.15,United States,Seattle,2021-10-16,bonus
1,E04105,Theodore Dinh,Technical Architect,IT,Manufacturing,Male,Asian,59,1997-11-29,99975,0.00,China,Chongqing,NaT,no bonus
2,E02572,Luna Sanders,Director,Finance,Speciality Products,Female,Caucasian,50,2006-10-26,163099,0.20,United States,Chicago,NaT,bonus
3,E02832,Penelope Jordan,Computer Systems Manager,IT,Manufacturing,Female,Caucasian,26,2019-09-27,84913,0.07,United States,Chicago,NaT,bonus
4,E01639,Austin Vo,Sr. Analyst,Finance,Manufacturing,Male,Asian,55,1995-11-20,95409,0.00,United States,Phoenix,NaT,no bonus

In [159]:
data = pd.read_excel("practice_1.xlsx")
print(data)

  First name  Last Name  Salary EEID
0       ross  tribbiani   20000   E1
1     rachel      bing    40000   E2
2     monica      green   25000   E7
3       joey     geller   60000   E8
4   chandler     buffay   33000   E4
5     phoebe      bing    45000   E5

In [160]:
data["Full Name"] = data["First name"] + " " + data["Last Name"]
print(data)

  First name  Last Name  Salary EEID        Full Name
0       ross  tribbiani   20000   E1   ross tribbiani
1     rachel      bing    40000   E2     rachel bing
2     monica      green   25000   E7     monica green
3       joey     geller   60000   E8      joey geller
4   chandler     buffay   33000   E4  chandler buffay
5     phoebe      bing    45000   E5     phoebe bing

In [161]:
data["Full Name"] = data["First name"].str.capitalize() + " " + data["Last Name"].str.capitalize() # memberikan huruf kapital
print(data)

  First name  Last Name  Salary EEID        Full Name
0       ross  tribbiani   20000   E1   Ross Tribbiani
1     rachel      bing    40000   E2     Rachel Bing
2     monica      green   25000   E7     Monica Green
3       joey     geller   60000   E8      Joey Geller
4   chandler     buffay   33000   E4  Chandler Buffay
5     phoebe      bing    45000   E5     Phoebe Bing

##### columns tranformation in pandas part-2

In [162]:
data = pd.read_excel("practice_1.xlsx")
print(data)

print("\n")
data["Bonus"] = (data["Salary"]/100)*20
print(data)

  First name  Last Name  Salary EEID
0       ross  tribbiani   20000   E1
1     rachel      bing    40000   E2
2     monica      green   25000   E7
3       joey     geller   60000   E8
4   chandler     buffay   33000   E4
5     phoebe      bing    45000   E5


  First name  Last Name  Salary EEID    Bonus
0       ross  tribbiani   20000   E1   4000.0
1     rachel      bing    40000   E2   8000.0
2     monica      green   25000   E7   5000.0
3       joey     geller   60000   E8  12000.0
4   chandler     buffay   33000   E4   6600.0
5     phoebe      bing    45000   E5   9000.0

In [163]:
data = {"Months" : ["January", "February", "March", "April"]}

a = pd.DataFrame(data)
print(a)
print("\n")

# mengambil beberapa huruf dari depan
def extract(value):
    return value[0:3]

a["Short_months"] = a["Months"].map(extract)
print(a)

     Months
0   January
1  February
2     March
3     April


     Months Short_months
0   January          Jan
1  February          Feb
2     March          Mar
3     April          Apr

##### group by in pandas

In [164]:
data = pd.read_excel("ESD.xlsx")
print(data.head(10))

     EEID        Full Name                 Job Title  Department  \
0  E02387      Emily Davis                Sr. Manger          IT
1  E04105    Theodore Dinh       Technical Architect          IT
2  E02572     Luna Sanders                  Director     Finance
3  E02832  Penelope Jordan  Computer Systems Manager          IT
4  E01639        Austin Vo               Sr. Analyst     Finance
5  E00644     Joshua Gupta    Account Representative       Sales
6  E01550      Ruby Barnes                   Manager          IT
7  E04332      Luke Martin                   Analyst     Finance
8  E04533    Easton Bailey                   Manager  Accounting
9  E03838  Madeline Walker               Sr. Analyst     Finance

            Business Unit  Gender  Ethnicity  Age  Hire Date  Annual Salary  \
0  Research & Development  Female      Black   55 2016-04-08         141604
1           Manufacturing    Male      Asian   59 1997-11-29          99975
2     Speciality Products  Female  Caucasian   50 2006-10-26         163099
3           Manufacturing  Female  Caucasian   26 2019-09-27          84913
4           Manufacturing    Male      Asian   55 1995-11-20          95409
5               Corporate    Male      Asian   57 2017-01-24          50994
6               Corporate  Female  Caucasian   27 2020-07-01         119746
7           Manufacturing    Male      Black   25 2020-05-16          41336
8           Manufacturing    Male  Caucasian   29 2019-01-25         113527
9     Speciality Products  Female  Caucasian   34 2018-06-13          77203

   Bonus %        Country       City  Exit Date
0     0.15  United States    Seattle 2021-10-16
1     0.00          China  Chongqing        NaT
2     0.20  United States    Chicago        NaT
3     0.07  United States    Chicago        NaT
4     0.00  United States    Phoenix        NaT
5     0.00          China  Chongqing        NaT
6     0.10  United States    Phoenix        NaT
7     0.00  United States      Miami 2021-05-20
8     0.06  United States     Austin        NaT
9     0.00  United States    Chicago        NaT

In [165]:
gp = data.groupby("Department").agg({"Gender" : "count"})
print(gp)

                 Gender
Department
Accounting           96
Engineering         158
Finance             120
Human Resources     125
IT                  241
Marketing           120
Sales               140

In [166]:
data = pd.read_excel("ESD.xlsx")
print(data.head(10))

     EEID        Full Name                 Job Title  Department  \
0  E02387      Emily Davis                Sr. Manger          IT
1  E04105    Theodore Dinh       Technical Architect          IT
2  E02572     Luna Sanders                  Director     Finance
3  E02832  Penelope Jordan  Computer Systems Manager          IT
4  E01639        Austin Vo               Sr. Analyst     Finance
5  E00644     Joshua Gupta    Account Representative       Sales
6  E01550      Ruby Barnes                   Manager          IT
7  E04332      Luke Martin                   Analyst     Finance
8  E04533    Easton Bailey                   Manager  Accounting
9  E03838  Madeline Walker               Sr. Analyst     Finance

            Business Unit  Gender  Ethnicity  Age  Hire Date  Annual Salary  \
0  Research & Development  Female      Black   55 2016-04-08         141604
1           Manufacturing    Male      Asian   59 1997-11-29          99975
2     Speciality Products  Female  Caucasian   50 2006-10-26         163099
3           Manufacturing  Female  Caucasian   26 2019-09-27          84913
4           Manufacturing    Male      Asian   55 1995-11-20          95409
5               Corporate    Male      Asian   57 2017-01-24          50994
6               Corporate  Female  Caucasian   27 2020-07-01         119746
7           Manufacturing    Male      Black   25 2020-05-16          41336
8           Manufacturing    Male  Caucasian   29 2019-01-25         113527
9     Speciality Products  Female  Caucasian   34 2018-06-13          77203

   Bonus %        Country       City  Exit Date
0     0.15  United States    Seattle 2021-10-16
1     0.00          China  Chongqing        NaT
2     0.20  United States    Chicago        NaT
3     0.07  United States    Chicago        NaT
4     0.00  United States    Phoenix        NaT
5     0.00          China  Chongqing        NaT
6     0.10  United States    Phoenix        NaT
7     0.00  United States      Miami 2021-05-20
8     0.06  United States     Austin        NaT
9     0.00  United States    Chicago        NaT

In [167]:
# groupby
gp = data.groupby("Job Title").agg({"EEID":"count"})
print(gp)

                                EEID
Job Title
Account Representative            21
Analyst                           51
Analyst II                        53
Automation Engineer                7
Business Partner                  19
Cloud Infrastructure Architect    15
Computer Systems Manager          21
Controls Engineer                 15
Development Engineer              19
Director                         121
Engineering Manager               20
Enterprise Architect              18
Field Engineer                    21
HRIS Analyst                      16
IT Coordinator                    11
IT Systems Architect              12
Manager                           98
Network Administrator             10
Network Architect                 18
Network Engineer                   7
Operations Engineer               12
Quality Engineer                  20
Service Desk Analyst              10
Solutions Architect               15
Sr. Account Representative         9
Sr. Analyst                       70
Sr. Business Partner              17
Sr. Manger                       110
System Administrator              15
Systems Analyst                   15
Technical Architect               17
Test Engineer                     12
Vice President                   105

In [168]:
gp = data.groupby("Department").agg({"EEID":"count"})
print(gp)

                 EEID
Department
Accounting         96
Engineering       158
Finance           120
Human Resources   125
IT                241
Marketing         120
Sales             140

In [169]:
gp = data.groupby(["Department", "Gender"]).agg({"EEID":"count"})
print(gp)

                        EEID
Department      Gender
Accounting      Female    53
                Male      43
Engineering     Female    80
                Male      78
Finance         Female    69
                Male      51
Human Resources Female    64
                Male      61
IT              Female   119
                Male     122
Marketing       Female    57
                Male      63
Sales           Female    76
                Male      64

In [170]:
gp1 = data.groupby("Country").agg({"Age" : "mean"})
print(gp1)

                     Age
Country
Brazil         43.654676
China          45.389908
United States  44.197512

In [171]:
gp1 = data.groupby("Country").agg({"Annual Salary" : "mean"})
print(gp1)

               Annual Salary
Country
Brazil         112324.834532
China          113823.532110
United States  113204.794712

In [172]:
gp1 = data.groupby("Country").agg({"Annual Salary" : "max"})
print(gp1)

               Annual Salary
Country
Brazil                258426
China                 257194
United States         258498

In [173]:
gp1 = data.groupby(["Country", "Gender"]).agg({"Annual Salary" : "max"})
print(gp1)

                      Annual Salary
Country       Gender
Brazil        Female         258426
              Male           249506
China         Female         249686
              Male           257194
United States Female         258498
              Male           258081

In [174]:
gp1 = data.groupby(["Country", "Gender"]).agg({"Annual Salary" : "max", "Age" : "min"})
print(gp1)

                      Annual Salary  Age
Country       Gender
Brazil        Female         258426   25
              Male           249506   26
China         Female         249686   25
              Male           257194   25
United States Female         258498   25
              Male           258081   25

##### merge, join and concatenate in pandas

In [175]:
data1 = {"Emp Id"   : ["EO1", "E02", "E03", "E04", "E05", "E06"],
        "Names"     : ["Ram", "Shym", "Rahul", "Vishal", "Ravi", "John"],
        "Age"       : [34, 56, 23, 44, 32, 36] }

data2 = {"Emp Id"   : ["E01", "E02", "E03", "E04", "E05", "E06"],
         "Salary"    :[45000, 56000, 34000, 30000, 50000, 62000]}

df1 = pd.DataFrame(data1)
df2 = pd.DataFrame(data2)

print(df1)
print()
print(df2)

  Emp Id   Names  Age
0    EO1     Ram   34
1    E02    Shym   56
2    E03   Rahul   23
3    E04  Vishal   44
4    E05    Ravi   32
5    E06    John   36

  Emp Id  Salary
0    E01   45000
1    E02   56000
2    E03   34000
3    E04   30000
4    E05   50000
5    E06   62000

In [176]:
# merge (gabungkan)
print (pd.merge(df1, df2, on = "Emp Id"))

  Emp Id   Names  Age  Salary
0    E02    Shym   56   56000
1    E03   Rahul   23   34000
2    E04  Vishal   44   30000
3    E05    Ravi   32   50000
4    E06    John   36   62000

In [177]:
data3 = {"Emp Id"   : ["E01", "E02", "E03", "E04", "E05", "E06"],
        "Names"     : ["Ram", "Shym", "Rahul", "Vishal", "Ravi", "John"],
        "Age"       : [34, 56, 23, 44, 32, 36] }

data4 = {"Emp Id"   : ["E01", "E07", "E03", "E04", "E08", "E06"],
         "Salary"    :[45000, 56000, 34000, 30000, 50000, 62000]}

df3 = pd.DataFrame(data3)
df4 = pd.DataFrame(data4)

print(df3)
print()
print(df4)

  Emp Id   Names  Age
0    E01     Ram   34
1    E02    Shym   56
2    E03   Rahul   23
3    E04  Vishal   44
4    E05    Ravi   32
5    E06    John   36

  Emp Id  Salary
0    E01   45000
1    E07   56000
2    E03   34000
3    E04   30000
4    E08   50000
5    E06   62000

In [178]:
# merge (gabungkan)
print(pd.merge(df3, df4, on = "Emp Id")) # digabungkan berdasarkan nilai yang sama pada kolom "Emp Id" (seperti subset di matematika)

  Emp Id   Names  Age  Salary
0    E01     Ram   34   45000
1    E03   Rahul   23   34000
2    E04  Vishal   44   30000
3    E06    John   36   62000

In [179]:
# semua data dari DataFrame kiri (df1) akan tetap ditampilkan,
# lalu pandas akan mencari data yang cocok di DataFrame kanan (df2),
# jika tidak ditemukan pasangan, maka nilainya akan diisi NaN.

# Metode ini berguna ketika kita ingin mempertahankan seluruh data utama pada tabel kiri sambil menambahkan informasi dari tabel kanan jika tersedia.

print(pd.merge(left=df3, right=df4, on="Emp Id", how="left"))

  Emp Id   Names  Age   Salary
0    E01     Ram   34  45000.0
1    E02    Shym   56      NaN
2    E03   Rahul   23  34000.0
3    E04  Vishal   44  30000.0
4    E05    Ravi   32      NaN
5    E06    John   36  62000.0

In [180]:
# Gabungkan df1 dan df2 berdasarkan "Emp Id",
# tampilkan semua data dari DataFrame kanan (df2),
# lalu ambil data yang cocok dari DataFrame kiri (df1).

# Jika tidak ada pasangan di df1, maka nilainya akan menjadi NaN.

print(pd.merge(left=df3, right=df4, on="Emp Id", how="right"))

  Emp Id   Names   Age  Salary
0    E01     Ram  34.0   45000
1    E07     NaN   NaN   56000
2    E03   Rahul  23.0   34000
3    E04  Vishal  44.0   30000
4    E08     NaN   NaN   50000
5    E06    John  36.0   62000

In [181]:
data5 = {"Emp Id"   : ["E01", "E02", "E03", "E04", "E05", "E06"],
        "Names"     : ["Ram", "Shym", "Rahul", "Vishal", "Ravi", "John"],
        "Age"       : [34, 56, 23, 44, 32, 36] }

data6 = {"Emp Id"   : ["E07", "E08", "E09", "E010", "E011", "E012"],
         "Names"    : ["bittu", "chintu", "pappu", "chotu", "bunty", "golu"],
         "Age"      : [34, 56, 23, 44, 32, 36]}

df5 = pd.DataFrame(data5)
df6 = pd.DataFrame(data6)

print (df5,"\n")
print(df6)

  Emp Id   Names  Age
0    E01     Ram   34
1    E02    Shym   56
2    E03   Rahul   23
3    E04  Vishal   44
4    E05    Ravi   32
5    E06    John   36

  Emp Id   Names  Age
0    E07   bittu   34
1    E08  chintu   56
2    E09   pappu   23
3   E010   chotu   44
4   E011   bunty   32
5   E012    golu   36

In [182]:
print(pd.concat([df5, df6])) # gabungkan semua data frame tanpa mengubah nilai mnejadi "NaN"

  Emp Id   Names  Age
0    E01     Ram   34
1    E02    Shym   56
2    E03   Rahul   23
3    E04  Vishal   44
4    E05    Ravi   32
5    E06    John   36
0    E07   bittu   34
1    E08  chintu   56
2    E09   pappu   23
3   E010   chotu   44
4   E011   bunty   32
5   E012    golu   36

##### pandas | compare DataFrame

In [183]:
import pandas as pd 

dict = {"Fruits"    : ["mango", "apples", "banana", "papaya"],
        "Price"     : [100, 150, 50, 35],
        "Quantity"  : [15, 10, 10, 3]}

df7 = pd.DataFrame(dict)
print(df7)

   Fruits  Price  Quantity
0   mango    100        15
1  apples    150        10
2  banana     50        10
3  papaya     35         3

In [184]:
df8 = df7.copy()
print(df8)

   Fruits  Price  Quantity
0   mango    100        15
1  apples    150        10
2  banana     50        10
3  papaya     35         3

In [185]:
# mengubah data pada posisi tertentu dalam DataFrame.
# mengedit nilai sesuai index baris dan kolomnya
# .loc dipakai untuk mengakses atau mengubah data berdasarkan: baris dan nama kolom
# DataFrame.loc[index_baris, "nama_kolom"] = nilai_baru
df8 = df7.copy()

df8.loc[0, "Price"] = 120
df8.loc[1, "Price"] = 175
df8.loc[3, "Price"] = 30
df8.loc[0, "Quantity"] = 12
df8.loc[1, "Quantity"] = 15
df8.loc[3, "Quantity"] = 5

print(df8)

# compare()
# melihat perubahan data dan hanya menampilkan nilai yang berubah (self --> awal other --> perubahan)
print()
print(df7.compare(df8))

   Fruits  Price  Quantity
0   mango    120        12
1  apples    175        15
2  banana     50        10
3  papaya     30         5

   Price        Quantity
    self  other     self other
0  100.0  120.0     15.0  12.0
1  150.0  175.0     10.0  15.0
3   35.0   30.0      3.0   5.0

In [186]:
# untuk melihat perubahan data pada banyak kolom
print(df7.compare(df8, align_axis = 0))

         Price  Quantity
0 self   100.0      15.0
  other  120.0      12.0
1 self   150.0      10.0
  other  175.0      15.0
3 self    35.0       3.0
  other   30.0       5.0

In [187]:
# melihat seluruh isi baris yang berubah dan membandingkan data lama vs baru secara lengkap
print(df7.compare(df8, keep_equal = True))

  Price       Quantity
   self other     self other
0   100   120       15    12
1   150   175       10    15
3    35    30        3     5

In [188]:
# menampilkan semua data walaupun tidak berubah, yg tidak berubah ditampilkan sebagai NaN
print(df7.compare(df8, keep_shape = True))

  Fruits        Price        Quantity
    self other   self  other     self other
0    NaN   NaN  100.0  120.0     15.0  12.0
1    NaN   NaN  150.0  175.0     10.0  15.0
2    NaN   NaN    NaN    NaN      NaN   NaN
3    NaN   NaN   35.0   30.0      3.0   5.0

In [189]:
# melihat perubahan data saja yg tidak berubah tidak di tampilkan
print(df7.compare(df8, keep_shape = False))

   Price        Quantity
    self  other     self other
0  100.0  120.0     15.0  12.0
1  150.0  175.0     10.0  15.0
3   35.0   30.0      3.0   5.0

##### comparre dataframes pandas

##### pivoting and melting dataframes

In [190]:
dict = {"keys"  : ["k1", "k2", "k1", "k2"],
        "Names" : ["John", "Ben", "David", "Peter"],
        "Houses": ["red", "blue", "green", "red"],
        "Grades": ["3rd", "8th", "9th", "8th"]}

df9 = pd.DataFrame(dict)
print(df9)

# mirip seperti pivot table di Excel
# keys dijadikan baris, Names dijadikan kolom, isi tabel diambil dari Houses dan Grades
print()
print(df9.pivot(index = "keys", columns = "Names", values = ["Houses", "Grades"]))

  keys  Names Houses Grades
0   k1   John    red    3rd
1   k2    Ben   blue    8th
2   k1  David  green    9th
3   k2  Peter    red    8th

      Houses                   Grades
Names    Ben  David John Peter    Ben David John Peter
keys
k1       NaN  green  red   NaN    NaN   9th  3rd   NaN
k2      blue    NaN  NaN   red    8th   NaN  NaN   8th

In [192]:
dict = {
        "Names" : ["John", "Ben", "David", "Peter"],
        "Houses": ["red", "blue", "green", "red"],
        "Grades": ["3rd", "8th", "9th", "8th"]}
df10 = pd.DataFrame(dict)
print(df10)

# melting
# digunakan untuk data preprocessing, visualisasi data, machine learning, statistik, mengubah data ke format long format
# cara baca ouput artinya: John data berasal dari kolom Houses nilainya red
print()
print(pd.melt(df10, id_vars = ["Names"], value_vars = ["Houses", "Grades"]))

   Names Houses Grades
0   John    red    3rd
1    Ben   blue    8th
2  David  green    9th
3  Peter    red    8th

   Names variable  value
0   John   Houses    red
1    Ben   Houses   blue
2  David   Houses  green
3  Peter   Houses    red
4   John   Grades    3rd
5    Ben   Grades    8th
6  David   Grades    9th
7  Peter   Grades    8th

In [194]:
# melting / melt
# nama kolom lebih jelas, mudah dipahami, sesuai kebutuhan laporan/analisis
print(pd.melt(df10, id_vars = ["Names"], value_vars = ["Houses", "Grades"], var_name = "Houses&Grades", value_name="values"))

   Names Houses&Grades values
0   John        Houses    red
1    Ben        Houses   blue
2  David        Houses  green
3  Peter        Houses    red
4   John        Grades    3rd
5    Ben        Grades    8th
6  David        Grades    9th
7  Peter        Grades    8th